Sleep: 750
Timeout:
    # slightly larger than a multiple of 3, which is the default TCP packet retransmission window
    Connect: 31
    Read: 61

Sources:
    'malwaredomainlist_com': 'https://www.malwaredomainlist.com/hostslist/hosts.txt'
    'someonewhocares_org': 'http://someonewhocares.org/hosts/zero/hosts'
    'mvps_org': 'http://winhelp2002.mvps.org/hosts.txt'
    'pgl_yoyo_org': 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext'
    'hosts-file_net_ad_servers': 'https://hosts-file.net/ad_servers.txt'
    'hosts-file_net_emd': 'https://hosts-file.net/emd.txt'
    'hosts-file_net_exp': 'https://hosts-file.net/exp.txt'
    'hosts-file_net_fsa': 'https://hosts-file.net/fsa.txt'
    'hosts-file_net_hjk': 'https://hosts-file.net/hjk.txt'
    'hosts-file_net_pha': 'https://hosts-file.net/pha.txt'
    'hosts-file_net_psh': 'https://hosts-file.net/psh.txt'
    'malwaredomains_com': 'https://mirror.cedia.org.ec/malwaredomains/justdomains'
